// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScopeId } from "./ScopeId";
import type { SymbolId } from "./SymbolId";

export interface Scope { parent: ScopeId | null, my_id: ScopeId, symbols: Array<SymbolId>, names: Array<string>, }