// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Function } from "./Function";
import type { MetaSymbolKind } from "./MetaSymbolKind";
import type { Mutability } from "./Mutability";
import type { SymbolId } from "./SymbolId";
import type { UserDefinedTypeName } from "./UserDefinedTypeName";

export type TypeEntrails = "None" | "Token" | { "Box": SymbolId } | { "Ref": [SymbolId, Mutability] } | { "Surrogate": SymbolId } | "Struct" | "Enum" | { "EnumVariant": SymbolId } | { "Vec": SymbolId } | "Trait" | { "Function": Function } | { "Option": SymbolId } | { "Clipped": MetaSymbolKind } | { "UserDefinedType": [MetaSymbolKind, UserDefinedTypeName] };