use crate::analysis::LookaheadDFA;
use crate::analysis::compiled_la_dfa::CompiledDFA;
use crate::config::{CommonGeneratorConfig, ParserGeneratorConfig};
use crate::generators::parser_ir::{
    ProductionIR,
    ProductionSymbolIR,
    build_production_ir,
    find_start_symbol_index as parser_ir_find_start_symbol_index,
    ordered_non_terminal_names as parser_ir_ordered_non_terminal_names,
};
use crate::generators::{GrammarConfig, NamingHelper};
use crate::{LRAction, LRParseTable};
use anyhow::Result;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

/// Generates the parser part of the parser output file for C# (LL(k)).
pub fn generate_parser_source<C: CommonGeneratorConfig + ParserGeneratorConfig>(
    grammar_config: &GrammarConfig,
    _lexer_source: &str, // Ignored, we regenerate the data class
    config: &C,
    la_dfa: &BTreeMap<String, LookaheadDFA>,
    _ast_type_has_lifetime: bool,
) -> Result<String> {
    generate_parser_source_internal(grammar_config, config, la_dfa)
}

fn generate_parser_source_internal<C: CommonGeneratorConfig + ParserGeneratorConfig>(
    grammar_config: &GrammarConfig,
    config: &C,
    la_dfa: &BTreeMap<String, LookaheadDFA>,
) -> Result<String> {
    let mut source = String::new();

    let non_terminal_names = parser_ir_ordered_non_terminal_names(grammar_config);
        let start_symbol_index = parser_ir_find_start_symbol_index(&non_terminal_names, grammar_config)?;
    let non_terminals = non_terminal_names.iter().collect::<Vec<_>>();

    let parser_type_name = NamingHelper::to_upper_camel_case(config.user_type_name()) + "Parser";

    writeln!(
        source,
        "// ---------------------------------------------------------"
    )?;
    writeln!(source, "// This file was generated by parol.")?;
    writeln!(source, "// Do not edit this file manually.")?;
    writeln!(source, "// Changes will be overwritten on the next build.")?;
    writeln!(
        source,
        "// ---------------------------------------------------------"
    )?;
    writeln!(source)?;

    writeln!(source, "using System;")?;
    writeln!(source, "using System.Collections.Generic;")?;
    writeln!(source, "using Parol.Runtime;")?;
    writeln!(source, "using Parol.Runtime.Scanner;")?;
    writeln!(source)?;
    writeln!(source, "namespace {} {{", config.module_name())?;
    writeln!(source, "    /// <summary>")?;
    writeln!(
        source,
        "    /// Parser facade generated by parol for this grammar."
    )?;
    writeln!(
        source,
        "    /// Provides parse tables and convenience entry points."
    )?;
    writeln!(source, "    /// </summary>")?;
    writeln!(source, "    public class {} {{", parser_type_name)?;

    // Lexer Source (Scanner data class only)
    let scanner_data =
        crate::generators::cs_lexer_generator::generate_scanner_data(grammar_config, config)?;
    writeln!(source, "{}", scanner_data)?;
    writeln!(source)?;

    // Max K
    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Maximum lookahead k used by the generated grammar."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        public const int MaxK = {};",
        grammar_config.lookahead_size
    )?;
    writeln!(source)?;

    // Non-Terminal Names
    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Ordered non-terminal names used by the parser tables."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        public static readonly string[] NonTerminalNames = ["
    )?;
    for name in &non_terminals {
        writeln!(source, "            \"{}\",", name)?;
    }
    writeln!(source, "        ];")?;
    writeln!(source)?;

    // Lookahead Automata
    generate_lookahead_automata(&mut source, la_dfa, &non_terminals)?;
    writeln!(source)?;

        let production_ir = build_production_ir(grammar_config, &non_terminal_names)?;
        generate_productions(&mut source, grammar_config, &production_ir)?;
    writeln!(source)?;

    // Parse Methods
    generate_parse_methods(&mut source, config, &parser_type_name, start_symbol_index)?;

    writeln!(source, "    }}")?;
    writeln!(source, "}}")?;

    Ok(source)
}

fn generate_lookahead_automata(
    source: &mut String,
    la_dfa: &BTreeMap<String, LookaheadDFA>,
    non_terminals: &[&String],
) -> Result<()> {
    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Lookahead DFAs indexed by non-terminal index."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        public static readonly LookaheadDfa[] LookaheadAutomata = ["
    )?;
    for (i, nt_name) in non_terminals.iter().enumerate() {
        if let Some(dfa) = la_dfa.get(*nt_name) {
            let compiled_dfa = CompiledDFA::from_lookahead_dfa(dfa);
            writeln!(source, "            /* {} - \"{}\" */", i, nt_name)?;
            writeln!(source, "            new(")?;
            writeln!(source, "                {},", compiled_dfa.prod0)?;
            writeln!(source, "                [")?;
            for t in &compiled_dfa.transitions {
                writeln!(
                    source,
                    "                    new({}, {}, {}, {}),",
                    t.from_state, t.term, t.to_state, t.prod_num
                )?;
            }
            writeln!(source, "                ],")?;
            writeln!(source, "                {} // k", compiled_dfa.k)?;
            writeln!(source, "            ),")?;
        }
    }
    writeln!(source, "        ];")?;
    Ok(())
}

fn generate_productions(
    source: &mut String,
    _grammar_config: &GrammarConfig,
    production_ir: &[ProductionIR],
) -> Result<()> {
    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Production table consumed by the LL(k) parser runtime."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        public static readonly Production[] Productions = ["
    )?;
    for p in production_ir {
        writeln!(source, "            // {} - {}", p.production_index, p.text)?;
        writeln!(source, "            new Production(")?;
        writeln!(source, "                {},", p.lhs_index)?;
        writeln!(source, "                [")?;
        for s in &p.rhs {
            match s {
                ProductionSymbolIR::NonTerminal(index) => {
                    writeln!(
                        source,
                        "                    new(ParseType.N, {}),",
                        index
                    )?;
                }
                ProductionSymbolIR::Terminal { index, clipped } => {
                    let parse_type = if *clipped {
                        "ParseType.C"
                    } else {
                        "ParseType.T"
                    };
                    writeln!(
                        source,
                        "                    new({}, {}),",
                        parse_type,
                        index
                    )?;
                }
            }
        }
        writeln!(source, "                ]")?;
        writeln!(source, "            ),")?;
    }
    writeln!(source, "        ];")?;
    Ok(())
}

fn generate_parse_methods(
    source: &mut String,
    config: &impl CommonGeneratorConfig,
    _parser_type_name: &str,
    start_symbol_index: usize,
) -> Result<()> {
    let scanner_type_name = NamingHelper::to_upper_camel_case(config.user_type_name()) + "Scanner";
    let actions_interface_name = format!(
        "I{}Actions",
        NamingHelper::to_upper_camel_case(config.user_type_name())
    );
    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Parses input with strongly typed user actions."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        /// <param name=\"input\">Input text to parse.</param>"
    )?;
    writeln!(
        source,
        "        /// <param name=\"fileName\">Logical file name used for diagnostics.</param>"
    )?;
    writeln!(
        source,
        "        /// <param name=\"userActions\">Typed semantic action receiver.</param>"
    )?;
    writeln!(
        source,
        "        public static void Parse(string input, string fileName, {} userActions) {{",
        actions_interface_name
    )?;
    writeln!(
        source,
        "            ParseInternal(input, fileName, userActions);"
    )?;
    writeln!(source, "        }}")?;
    writeln!(source)?;

    writeln!(
        source,
        "        private static void ParseInternal(string input, string fileName, IUserActions userActions) {{"
    )?;
    writeln!(source, "            var parser = new LLKParser(")?;
    writeln!(source, "                {},", start_symbol_index)?;
    writeln!(source, "                LookaheadAutomata,")?;
    writeln!(source, "                Productions,")?;
    writeln!(
        source,
        "                {}Data.TerminalNames,",
        scanner_type_name
    )?;
    writeln!(source, "                NonTerminalNames")?;
    writeln!(source, "            );")?;
    writeln!(source)?;
    writeln!(
        source,
        "            var tokens = Scanner.Scan(input, fileName, {}Data.MatchFunction, {}Data.ScannerModes);",
        scanner_type_name, scanner_type_name
    )?;
    writeln!(
        source,
        "            parser.Parse(tokens, userActions, fileName);"
    )?;
    writeln!(source, "        }}")?;

    Ok(())
}

/// Generates the parser part of the parser output file for C# (LALR(1)).
pub fn generate_lalr1_parser_source<C: CommonGeneratorConfig + ParserGeneratorConfig>(
    grammar_config: &GrammarConfig,
    _lexer_source: &str,
    config: &C,
    parse_table: &LRParseTable,
    _ast_type_has_lifetime: bool,
) -> Result<String> {
    generate_lalr1_parser_source_internal(grammar_config, config, parse_table)
}

fn generate_lalr1_parser_source_internal<C: CommonGeneratorConfig + ParserGeneratorConfig>(
    grammar_config: &GrammarConfig,
    config: &C,
    parse_table: &LRParseTable,
) -> Result<String> {
    let mut source = String::new();

    let non_terminal_names = parser_ir_ordered_non_terminal_names(grammar_config);
    let start_symbol_index =
        parser_ir_find_start_symbol_index(&non_terminal_names, grammar_config)?;
    let non_terminals = non_terminal_names.iter().collect::<Vec<_>>();
    let production_ir = build_production_ir(grammar_config, &non_terminal_names)?;

    let parser_type_name = NamingHelper::to_upper_camel_case(config.user_type_name()) + "Parser";

    writeln!(
        source,
        "// ---------------------------------------------------------"
    )?;
    writeln!(source, "// This file was generated by parol.")?;
    writeln!(source, "// Do not edit this file manually.")?;
    writeln!(source, "// Changes will be overwritten on the next build.")?;
    writeln!(
        source,
        "// ---------------------------------------------------------"
    )?;
    writeln!(source)?;

    writeln!(source, "using System;")?;
    writeln!(source, "using System.Collections.Generic;")?;
    writeln!(source, "using Parol.Runtime;")?;
    writeln!(source, "using Parol.Runtime.Scanner;")?;
    writeln!(source)?;
    writeln!(source, "namespace {} {{", config.module_name())?;
    writeln!(source, "    /// <summary>")?;
    writeln!(
        source,
        "    /// LALR(1) parser facade generated by parol for this grammar."
    )?;
    writeln!(
        source,
        "    /// Provides parse table data and convenience entry points."
    )?;
    writeln!(source, "    /// </summary>")?;
    writeln!(source, "    public class {} {{", parser_type_name)?;

    let scanner_data =
        crate::generators::cs_lexer_generator::generate_scanner_data(grammar_config, config)?;
    writeln!(source, "{}", scanner_data)?;
    writeln!(source)?;

    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Ordered non-terminal names used by parser diagnostics."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        public static readonly string[] NonTerminalNames = ["
    )?;
    for name in &non_terminals {
        writeln!(source, "            \"{}\",", name)?;
    }
    writeln!(source, "        ];")?;
    writeln!(source)?;

    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// LALR(1) production metadata consumed by the parser runtime."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        public static readonly LRProduction[] Productions = ["
    )?;
    for p in &production_ir {
        writeln!(source, "            // {} - {}", p.production_index, p.text)?;
        writeln!(source, "            new LRProduction({}, [", p.lhs_index)?;
        for s in &p.rhs {
            let is_semantic_child = match s {
                ProductionSymbolIR::NonTerminal(..) => true,
                ProductionSymbolIR::Terminal { clipped, .. } => !*clipped,
            };
            writeln!(
                source,
                "                {},",
                if is_semantic_child { "true" } else { "false" }
            )?;
        }
        writeln!(source, "            ]),")?;
    }
    writeln!(source, "        ];")?;
    writeln!(source)?;

    emit_lalr_parse_table(&mut source, parse_table)?;
    writeln!(source)?;

    emit_lalr_parse_methods(&mut source, config, &parser_type_name, start_symbol_index)?;

    writeln!(source, "    }}")?;
    writeln!(source, "}}")?;

    Ok(source)
}

fn emit_lalr_parse_table(source: &mut String, parse_table: &LRParseTable) -> Result<()> {
    let actions = parse_table
        .states
        .iter()
        .fold(BTreeSet::<LRAction>::new(), |mut acc, s| {
            s.actions.iter().for_each(|(_, a)| {
                acc.insert(a.clone());
            });
            acc
        })
        .into_iter()
        .collect::<Vec<_>>();

    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Canonical LALR(1) parse table used by the parser runtime."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        public static readonly LRParseTable ParseTable = new("
    )?;

    writeln!(source, "            [")?;
    for (i, action) in actions.iter().enumerate() {
        writeln!(
            source,
            "                /* {} */ {},",
            i,
            render_lalr_action(action)
        )?;
    }
    writeln!(source, "            ],")?;

    writeln!(source, "            [")?;
    for (state_num, state) in parse_table.states.iter().enumerate() {
        writeln!(source, "                // State {}", state_num)?;
        writeln!(source, "                new LR1State(")?;

        writeln!(source, "                    [")?;
        for (terminal, action) in &state.actions {
            let action_index = actions
                .iter()
                .position(|a| a == action)
                .expect("Action must exist in global action list");
            writeln!(
                source,
                "                        new LRActionRef({}, {}),",
                terminal, action_index
            )?;
        }
        writeln!(source, "                    ],")?;

        writeln!(source, "                    [")?;
        for (non_terminal, goto_state) in &state.gotos {
            writeln!(
                source,
                "                        new LRGoto({}, {}),",
                non_terminal, goto_state
            )?;
        }
        writeln!(source, "                    ]")?;
        writeln!(source, "                ),")?;
    }
    writeln!(source, "            ]")?;
    writeln!(source, "        );")?;

    Ok(())
}

fn render_lalr_action(action: &LRAction) -> String {
    match action {
        LRAction::Shift(state) => format!("new LRAction.Shift({})", state),
        LRAction::Reduce(non_terminal, production) => {
            format!("new LRAction.Reduce({}, {})", non_terminal, production)
        }
        LRAction::Accept => "new LRAction.Accept()".to_string(),
    }
}

fn emit_lalr_parse_methods(
    source: &mut String,
    config: &impl CommonGeneratorConfig,
    _parser_type_name: &str,
    start_symbol_index: usize,
) -> Result<()> {
    let scanner_type_name = NamingHelper::to_upper_camel_case(config.user_type_name()) + "Scanner";
    let actions_interface_name = format!(
        "I{}Actions",
        NamingHelper::to_upper_camel_case(config.user_type_name())
    );
    writeln!(source, "        /// <summary>")?;
    writeln!(
        source,
        "        /// Parses input with strongly typed user actions."
    )?;
    writeln!(source, "        /// </summary>")?;
    writeln!(
        source,
        "        /// <param name=\"input\">Input text to parse.</param>"
    )?;
    writeln!(
        source,
        "        /// <param name=\"fileName\">Logical file name used for diagnostics.</param>"
    )?;
    writeln!(
        source,
        "        /// <param name=\"userActions\">Typed semantic action receiver.</param>"
    )?;
    writeln!(
        source,
        "        public static void Parse(string input, string fileName, {} userActions) {{",
        actions_interface_name
    )?;
    writeln!(
        source,
        "            ParseInternal(input, fileName, userActions);"
    )?;
    writeln!(source, "        }}")?;
    writeln!(source)?;

    writeln!(
        source,
        "        private static void ParseInternal(string input, string fileName, IUserActions userActions) {{"
    )?;
    writeln!(source, "            var parser = new LRParser(")?;
    writeln!(source, "                {},", start_symbol_index)?;
    writeln!(source, "                ParseTable,")?;
    writeln!(source, "                Productions,")?;
    writeln!(
        source,
        "                {}Data.TerminalNames,",
        scanner_type_name
    )?;
    writeln!(source, "                NonTerminalNames")?;
    writeln!(source, "            );")?;
    writeln!(source)?;
    writeln!(
        source,
        "            var tokens = Scanner.Scan(input, fileName, {}Data.MatchFunction, {}Data.ScannerModes);",
        scanner_type_name, scanner_type_name
    )?;
    writeln!(
        source,
        "            parser.Parse(tokens, userActions, fileName);"
    )?;
    writeln!(source, "        }}")?;

    Ok(())
}
