// ---------------------------------------------------------
// This file was generated by parol.
// Do not edit this file manually.
// Changes will be overwritten on the next build.
// ---------------------------------------------------------

use parol_runtime::{
    ParolError, ParseTree, TokenStream,
    parser::{
        LLKParser, LookaheadDFA, ParseType, Production, Trans, parse_tree_type::TreeConstruct,
    },
};
use scnr2::scanner;
use std::path::Path;

use crate::parol_ls_grammar::ParolLsGrammar;
use crate::parol_ls_grammar_trait::ParolLsGrammarAuto;

pub const TERMINAL_NAMES: &[&str; 47] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "PercentStart",
    /*  6 */ "PercentTitle",
    /*  7 */ "PercentComment",
    /*  8 */ "PercentUserUnderscoreType",
    /*  9 */ "Equ",
    /* 10 */ "PercentNtUnderscoreType",
    /* 11 */ "PercentTUnderscoreType",
    /* 12 */ "PercentGrammarUnderscoreType",
    /* 13 */ "PercentLineUnderscoreComment",
    /* 14 */ "PercentBlockUnderscoreComment",
    /* 15 */ "PercentAutoUnderscoreNewlineUnderscoreOff",
    /* 16 */ "PercentAutoUnderscoreWsUnderscoreOff",
    /* 17 */ "PercentSkip",
    /* 18 */ "PercentOn",
    /* 19 */ "PercentAllowUnderscoreUnmatched",
    /* 20 */ "PercentEnter",
    /* 21 */ "PercentPush",
    /* 22 */ "PercentPop",
    /* 23 */ "PercentPercent",
    /* 24 */ "DoubleColon",
    /* 25 */ "Colon",
    /* 26 */ "Semicolon",
    /* 27 */ "Or",
    /* 28 */ "LT",
    /* 29 */ "GT",
    /* 30 */ "LParen",
    /* 31 */ "RParen",
    /* 32 */ "LBracket",
    /* 33 */ "RBracket",
    /* 34 */ "LBrace",
    /* 35 */ "RBrace",
    /* 36 */ "Identifier",
    /* 37 */ "String",
    /* 38 */ "LiteralString",
    /* 39 */ "PercentScanner",
    /* 40 */ "Comma",
    /* 41 */ "At",
    /* 42 */ "CutOperator",
    /* 43 */ "Regex",
    /* 44 */ "PositiveLookahead",
    /* 45 */ "NegativeLookahead",
    /* 46 */ "Error",
];

scanner! {
    ParolLsGrammarScanner {
        mode INITIAL {
            token r"\r\n|\r|\n" => 1; // "Newline"
            token r"[\s--\r\n]+" => 2; // "Whitespace"
            token r"//.*(\r\n|\r|\n)?" => 3; // "LineComment"
            token r"/\*/?([^/]|[^*]/)*\*/" => 4; // "BlockComment"
            token r"%start" => 5; // "PercentStart"
            token r"%title" => 6; // "PercentTitle"
            token r"%comment" => 7; // "PercentComment"
            token r"%user_type" => 8; // "PercentUserUnderscoreType"
            token r"=" => 9; // "Equ"
            token r"%nt_type" => 10; // "PercentNtUnderscoreType"
            token r"%t_type" => 11; // "PercentTUnderscoreType"
            token r"%grammar_type" => 12; // "PercentGrammarUnderscoreType"
            token r"%line_comment" => 13; // "PercentLineUnderscoreComment"
            token r"%block_comment" => 14; // "PercentBlockUnderscoreComment"
            token r"%auto_newline_off" => 15; // "PercentAutoUnderscoreNewlineUnderscoreOff"
            token r"%auto_ws_off" => 16; // "PercentAutoUnderscoreWsUnderscoreOff"
            token r"%skip" => 17; // "PercentSkip"
            token r"%on" => 18; // "PercentOn"
            token r"%allow_unmatched" => 19; // "PercentAllowUnderscoreUnmatched"
            token r"%enter" => 20; // "PercentEnter"
            token r"%push" => 21; // "PercentPush"
            token r"%pop" => 22; // "PercentPop"
            token r"%%" => 23; // "PercentPercent"
            token r"::" => 24; // "DoubleColon"
            token r":" => 25; // "Colon"
            token r";" => 26; // "Semicolon"
            token r"\|" => 27; // "Or"
            token r"<" => 28; // "LT"
            token r">" => 29; // "GT"
            token r"\(" => 30; // "LParen"
            token r"\)" => 31; // "RParen"
            token r"\[" => 32; // "LBracket"
            token r"\]" => 33; // "RBracket"
            token r"\{" => 34; // "LBrace"
            token r"\}" => 35; // "RBrace"
            token r"[a-zA-Z_][a-zA-Z0-9_]*" => 36; // "Identifier"
            token r#""(\\.|[^"])*""# => 37; // "String"
            token r"'(\\.|[^'])*'" => 38; // "LiteralString"
            token r"%scanner" => 39; // "PercentScanner"
            token r"," => 40; // "Comma"
            token r"@" => 41; // "At"
            token r"\^" => 42; // "CutOperator"
            token r"/(\\.|[^\/])*/" => 43; // "Regex"
            token r"\?=" => 44; // "PositiveLookahead"
            token r"\?!" => 45; // "NegativeLookahead"
            token r"." => 46; // "Error"
        }
    }
}

const MAX_K: usize = 1;
pub const SKIP_TOKENS_BY_SCANNER_STATE: &[&[parol_runtime::TerminalIndex]; 1] = &[&[]];

pub const NON_TERMINALS: &[&str; 50] = &[
    /*  0 */ "ASTControl",
    /*  1 */ "ASTControlOpt",
    /*  2 */ "Alternation",
    /*  3 */ "AlternationList",
    /*  4 */ "Alternations",
    /*  5 */ "AlternationsList",
    /*  6 */ "CutOperator",
    /*  7 */ "Declaration",
    /*  8 */ "DoubleColon",
    /*  9 */ "Factor",
    /* 10 */ "GrammarDefinition",
    /* 11 */ "GrammarDefinitionList",
    /* 12 */ "Group",
    /* 13 */ "Identifier",
    /* 14 */ "IdentifierList",
    /* 15 */ "IdentifierListList",
    /* 16 */ "LiteralString",
    /* 17 */ "LookAhead",
    /* 18 */ "LookAheadGroup",
    /* 19 */ "MemberName",
    /* 20 */ "NegativeLookahead",
    /* 21 */ "NonTerminal",
    /* 22 */ "NonTerminalOpt",
    /* 23 */ "Optional",
    /* 24 */ "ParolLs",
    /* 25 */ "PositiveLookahead",
    /* 26 */ "Production",
    /* 27 */ "ProductionLHS",
    /* 28 */ "Prolog",
    /* 29 */ "PrologList",
    /* 30 */ "PrologList0",
    /* 31 */ "Regex",
    /* 32 */ "Repeat",
    /* 33 */ "ScannerDirectives",
    /* 34 */ "ScannerState",
    /* 35 */ "ScannerStateDirectives",
    /* 36 */ "ScannerStateList",
    /* 37 */ "SimpleToken",
    /* 38 */ "SimpleTokenOpt",
    /* 39 */ "StartDeclaration",
    /* 40 */ "String",
    /* 41 */ "Symbol",
    /* 42 */ "TokenExpression",
    /* 43 */ "TokenExpressionOpt",
    /* 44 */ "TokenLiteral",
    /* 45 */ "TokenWithStates",
    /* 46 */ "TokenWithStatesOpt",
    /* 47 */ "UserTypeDeclaration",
    /* 48 */ "UserTypeName",
    /* 49 */ "UserTypeNameList",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 50] = &[
    /* 0 - "ASTControl" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 3, 72),
            Trans(0, 41, 2, 71),
            Trans(0, 42, 1, 70),
        ],
        k: 1,
    },
    /* 1 - "ASTControlOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 1, 73),
            Trans(0, 26, 2, 74),
            Trans(0, 27, 2, 74),
            Trans(0, 28, 2, 74),
            Trans(0, 30, 2, 74),
            Trans(0, 31, 2, 74),
            Trans(0, 32, 2, 74),
            Trans(0, 33, 2, 74),
            Trans(0, 34, 2, 74),
            Trans(0, 35, 2, 74),
            Trans(0, 36, 2, 74),
            Trans(0, 37, 2, 74),
            Trans(0, 38, 2, 74),
            Trans(0, 43, 2, 74),
        ],
        k: 1,
    },
    /* 2 - "Alternation" */
    LookaheadDFA {
        prod0: 33,
        transitions: &[],
        k: 0,
    },
    /* 3 - "AlternationList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 26, 2, 35),
            Trans(0, 27, 2, 35),
            Trans(0, 28, 1, 34),
            Trans(0, 30, 1, 34),
            Trans(0, 31, 2, 35),
            Trans(0, 32, 1, 34),
            Trans(0, 33, 2, 35),
            Trans(0, 34, 1, 34),
            Trans(0, 35, 2, 35),
            Trans(0, 36, 1, 34),
            Trans(0, 37, 1, 34),
            Trans(0, 38, 1, 34),
            Trans(0, 43, 1, 34),
        ],
        k: 1,
    },
    /* 4 - "Alternations" */
    LookaheadDFA {
        prod0: 30,
        transitions: &[],
        k: 0,
    },
    /* 5 - "AlternationsList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 26, 2, 32),
            Trans(0, 27, 1, 31),
            Trans(0, 31, 2, 32),
            Trans(0, 33, 2, 32),
            Trans(0, 35, 2, 32),
        ],
        k: 1,
    },
    /* 6 - "CutOperator" */
    LookaheadDFA {
        prod0: 76,
        transitions: &[],
        k: 0,
    },
    /* 7 - "Declaration" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 6, 1, 7),
            Trans(0, 7, 2, 8),
            Trans(0, 8, 3, 9),
            Trans(0, 10, 4, 10),
            Trans(0, 11, 5, 11),
            Trans(0, 12, 6, 12),
            Trans(0, 13, 7, 13),
            Trans(0, 14, 7, 13),
            Trans(0, 15, 7, 13),
            Trans(0, 16, 7, 13),
            Trans(0, 17, 7, 13),
            Trans(0, 18, 7, 13),
            Trans(0, 19, 7, 13),
        ],
        k: 1,
    },
    /* 8 - "DoubleColon" */
    LookaheadDFA {
        prod0: 27,
        transitions: &[],
        k: 0,
    },
    /* 9 - "Factor" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 28, 4, 39),
            Trans(0, 30, 1, 36),
            Trans(0, 32, 3, 38),
            Trans(0, 34, 2, 37),
            Trans(0, 36, 4, 39),
            Trans(0, 37, 4, 39),
            Trans(0, 38, 4, 39),
            Trans(0, 43, 4, 39),
        ],
        k: 1,
    },
    /* 10 - "GrammarDefinition" */
    LookaheadDFA {
        prod0: 24,
        transitions: &[],
        k: 0,
    },
    /* 11 - "GrammarDefinitionList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 0, 2, 26), Trans(0, 36, 1, 25)],
        k: 1,
    },
    /* 12 - "Group" */
    LookaheadDFA {
        prod0: 55,
        transitions: &[],
        k: 0,
    },
    /* 13 - "Identifier" */
    LookaheadDFA {
        prod0: 61,
        transitions: &[],
        k: 0,
    },
    /* 14 - "IdentifierList" */
    LookaheadDFA {
        prod0: 67,
        transitions: &[],
        k: 0,
    },
    /* 15 - "IdentifierListList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 6, 2, 69),
            Trans(0, 7, 2, 69),
            Trans(0, 8, 2, 69),
            Trans(0, 10, 2, 69),
            Trans(0, 11, 2, 69),
            Trans(0, 12, 2, 69),
            Trans(0, 13, 2, 69),
            Trans(0, 14, 2, 69),
            Trans(0, 15, 2, 69),
            Trans(0, 16, 2, 69),
            Trans(0, 17, 2, 69),
            Trans(0, 18, 2, 69),
            Trans(0, 19, 2, 69),
            Trans(0, 20, 2, 69),
            Trans(0, 21, 2, 69),
            Trans(0, 22, 2, 69),
            Trans(0, 23, 2, 69),
            Trans(0, 29, 2, 69),
            Trans(0, 35, 2, 69),
            Trans(0, 39, 2, 69),
            Trans(0, 40, 1, 68),
        ],
        k: 1,
    },
    /* 16 - "LiteralString" */
    LookaheadDFA {
        prod0: 63,
        transitions: &[],
        k: 0,
    },
    /* 17 - "LookAhead" */
    LookaheadDFA {
        prod0: 82,
        transitions: &[],
        k: 0,
    },
    /* 18 - "LookAheadGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 44, 1, 83), Trans(0, 45, 2, 84)],
        k: 1,
    },
    /* 19 - "MemberName" */
    LookaheadDFA {
        prod0: 75,
        transitions: &[],
        k: 0,
    },
    /* 20 - "NegativeLookahead" */
    LookaheadDFA {
        prod0: 86,
        transitions: &[],
        k: 0,
    },
    /* 21 - "NonTerminal" */
    LookaheadDFA {
        prod0: 58,
        transitions: &[],
        k: 0,
    },
    /* 22 - "NonTerminalOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 1, 59),
            Trans(0, 26, 2, 60),
            Trans(0, 27, 2, 60),
            Trans(0, 28, 2, 60),
            Trans(0, 30, 2, 60),
            Trans(0, 31, 2, 60),
            Trans(0, 32, 2, 60),
            Trans(0, 33, 2, 60),
            Trans(0, 34, 2, 60),
            Trans(0, 35, 2, 60),
            Trans(0, 36, 2, 60),
            Trans(0, 37, 2, 60),
            Trans(0, 38, 2, 60),
            Trans(0, 41, 1, 59),
            Trans(0, 42, 1, 59),
            Trans(0, 43, 2, 60),
        ],
        k: 1,
    },
    /* 23 - "Optional" */
    LookaheadDFA {
        prod0: 56,
        transitions: &[],
        k: 0,
    },
    /* 24 - "ParolLs" */
    LookaheadDFA {
        prod0: 0,
        transitions: &[],
        k: 0,
    },
    /* 25 - "PositiveLookahead" */
    LookaheadDFA {
        prod0: 85,
        transitions: &[],
        k: 0,
    },
    /* 26 - "Production" */
    LookaheadDFA {
        prod0: 29,
        transitions: &[],
        k: 0,
    },
    /* 27 - "ProductionLHS" */
    LookaheadDFA {
        prod0: 28,
        transitions: &[],
        k: 0,
    },
    /* 28 - "Prolog" */
    LookaheadDFA {
        prod0: 1,
        transitions: &[],
        k: 0,
    },
    /* 29 - "PrologList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 6, 1, 4),
            Trans(0, 7, 1, 4),
            Trans(0, 8, 1, 4),
            Trans(0, 10, 1, 4),
            Trans(0, 11, 1, 4),
            Trans(0, 12, 1, 4),
            Trans(0, 13, 1, 4),
            Trans(0, 14, 1, 4),
            Trans(0, 15, 1, 4),
            Trans(0, 16, 1, 4),
            Trans(0, 17, 1, 4),
            Trans(0, 18, 1, 4),
            Trans(0, 19, 1, 4),
            Trans(0, 23, 2, 5),
            Trans(0, 39, 2, 5),
        ],
        k: 1,
    },
    /* 30 - "PrologList0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 23, 2, 3), Trans(0, 39, 1, 2)],
        k: 1,
    },
    /* 31 - "Regex" */
    LookaheadDFA {
        prod0: 81,
        transitions: &[],
        k: 0,
    },
    /* 32 - "Repeat" */
    LookaheadDFA {
        prod0: 57,
        transitions: &[],
        k: 0,
    },
    /* 33 - "ScannerDirectives" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 13, 1, 14),
            Trans(0, 14, 2, 15),
            Trans(0, 15, 3, 16),
            Trans(0, 16, 4, 17),
            Trans(0, 17, 5, 18),
            Trans(0, 18, 6, 19),
            Trans(0, 19, 7, 20),
        ],
        k: 1,
    },
    /* 34 - "ScannerState" */
    LookaheadDFA {
        prod0: 64,
        transitions: &[],
        k: 0,
    },
    /* 35 - "ScannerStateDirectives" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 20, 1, 21),
            Trans(0, 21, 2, 22),
            Trans(0, 22, 3, 23),
        ],
        k: 1,
    },
    /* 36 - "ScannerStateList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 13, 1, 65),
            Trans(0, 14, 1, 65),
            Trans(0, 15, 1, 65),
            Trans(0, 16, 1, 65),
            Trans(0, 17, 1, 65),
            Trans(0, 18, 1, 65),
            Trans(0, 19, 1, 65),
            Trans(0, 35, 2, 66),
        ],
        k: 1,
    },
    /* 37 - "SimpleToken" */
    LookaheadDFA {
        prod0: 49,
        transitions: &[],
        k: 0,
    },
    /* 38 - "SimpleTokenOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 1, 50),
            Trans(0, 26, 2, 51),
            Trans(0, 27, 2, 51),
            Trans(0, 28, 2, 51),
            Trans(0, 30, 2, 51),
            Trans(0, 31, 2, 51),
            Trans(0, 32, 2, 51),
            Trans(0, 33, 2, 51),
            Trans(0, 34, 2, 51),
            Trans(0, 35, 2, 51),
            Trans(0, 36, 2, 51),
            Trans(0, 37, 2, 51),
            Trans(0, 38, 2, 51),
            Trans(0, 41, 1, 50),
            Trans(0, 42, 1, 50),
            Trans(0, 43, 2, 51),
        ],
        k: 1,
    },
    /* 39 - "StartDeclaration" */
    LookaheadDFA {
        prod0: 6,
        transitions: &[],
        k: 0,
    },
    /* 40 - "String" */
    LookaheadDFA {
        prod0: 62,
        transitions: &[],
        k: 0,
    },
    /* 41 - "Symbol" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 28, 3, 42),
            Trans(0, 36, 1, 40),
            Trans(0, 37, 2, 41),
            Trans(0, 38, 2, 41),
            Trans(0, 43, 2, 41),
        ],
        k: 1,
    },
    /* 42 - "TokenExpression" */
    LookaheadDFA {
        prod0: 46,
        transitions: &[],
        k: 0,
    },
    /* 43 - "TokenExpressionOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 2, 48),
            Trans(0, 26, 2, 48),
            Trans(0, 27, 2, 48),
            Trans(0, 28, 2, 48),
            Trans(0, 30, 2, 48),
            Trans(0, 31, 2, 48),
            Trans(0, 32, 2, 48),
            Trans(0, 33, 2, 48),
            Trans(0, 34, 2, 48),
            Trans(0, 35, 2, 48),
            Trans(0, 36, 2, 48),
            Trans(0, 37, 2, 48),
            Trans(0, 38, 2, 48),
            Trans(0, 41, 2, 48),
            Trans(0, 42, 2, 48),
            Trans(0, 43, 2, 48),
            Trans(0, 44, 1, 47),
            Trans(0, 45, 1, 47),
        ],
        k: 1,
    },
    /* 44 - "TokenLiteral" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 37, 1, 43),
            Trans(0, 38, 2, 44),
            Trans(0, 43, 3, 45),
        ],
        k: 1,
    },
    /* 45 - "TokenWithStates" */
    LookaheadDFA {
        prod0: 52,
        transitions: &[],
        k: 0,
    },
    /* 46 - "TokenWithStatesOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 1, 53),
            Trans(0, 26, 2, 54),
            Trans(0, 27, 2, 54),
            Trans(0, 28, 2, 54),
            Trans(0, 30, 2, 54),
            Trans(0, 31, 2, 54),
            Trans(0, 32, 2, 54),
            Trans(0, 33, 2, 54),
            Trans(0, 34, 2, 54),
            Trans(0, 35, 2, 54),
            Trans(0, 36, 2, 54),
            Trans(0, 37, 2, 54),
            Trans(0, 38, 2, 54),
            Trans(0, 41, 1, 53),
            Trans(0, 42, 1, 53),
            Trans(0, 43, 2, 54),
        ],
        k: 1,
    },
    /* 47 - "UserTypeDeclaration" */
    LookaheadDFA {
        prod0: 77,
        transitions: &[],
        k: 0,
    },
    /* 48 - "UserTypeName" */
    LookaheadDFA {
        prod0: 78,
        transitions: &[],
        k: 0,
    },
    /* 49 - "UserTypeNameList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 6, 2, 80),
            Trans(0, 7, 2, 80),
            Trans(0, 8, 2, 80),
            Trans(0, 10, 2, 80),
            Trans(0, 11, 2, 80),
            Trans(0, 12, 2, 80),
            Trans(0, 13, 2, 80),
            Trans(0, 14, 2, 80),
            Trans(0, 15, 2, 80),
            Trans(0, 16, 2, 80),
            Trans(0, 17, 2, 80),
            Trans(0, 18, 2, 80),
            Trans(0, 19, 2, 80),
            Trans(0, 23, 2, 80),
            Trans(0, 24, 1, 79),
            Trans(0, 26, 2, 80),
            Trans(0, 27, 2, 80),
            Trans(0, 28, 2, 80),
            Trans(0, 30, 2, 80),
            Trans(0, 31, 2, 80),
            Trans(0, 32, 2, 80),
            Trans(0, 33, 2, 80),
            Trans(0, 34, 2, 80),
            Trans(0, 35, 2, 80),
            Trans(0, 36, 2, 80),
            Trans(0, 37, 2, 80),
            Trans(0, 38, 2, 80),
            Trans(0, 39, 2, 80),
            Trans(0, 43, 2, 80),
        ],
        k: 1,
    },
];

pub const PRODUCTIONS: &[Production; 87] = &[
    // 0 - ParolLs: Prolog GrammarDefinition;
    Production {
        lhs: 24,
        production: &[ParseType::N(10), ParseType::N(28)],
    },
    // 1 - Prolog: StartDeclaration PrologList /* Vec */ PrologList0 /* Vec */;
    Production {
        lhs: 28,
        production: &[ParseType::N(30), ParseType::N(29), ParseType::N(39)],
    },
    // 2 - PrologList0: ScannerState PrologList0;
    Production {
        lhs: 30,
        production: &[ParseType::N(30), ParseType::N(34)],
    },
    // 3 - PrologList0: ;
    Production {
        lhs: 30,
        production: &[],
    },
    // 4 - PrologList: Declaration PrologList;
    Production {
        lhs: 29,
        production: &[ParseType::N(29), ParseType::N(7)],
    },
    // 5 - PrologList: ;
    Production {
        lhs: 29,
        production: &[],
    },
    // 6 - StartDeclaration: "%start" Identifier;
    Production {
        lhs: 39,
        production: &[ParseType::N(13), ParseType::T(5)],
    },
    // 7 - Declaration: "%title" String;
    Production {
        lhs: 7,
        production: &[ParseType::N(40), ParseType::T(6)],
    },
    // 8 - Declaration: "%comment" String;
    Production {
        lhs: 7,
        production: &[ParseType::N(40), ParseType::T(7)],
    },
    // 9 - Declaration: "%user_type" Identifier "=" UserTypeName;
    Production {
        lhs: 7,
        production: &[
            ParseType::N(48),
            ParseType::T(9),
            ParseType::N(13),
            ParseType::T(8),
        ],
    },
    // 10 - Declaration: "%nt_type" Identifier@nt_name "=" UserTypeName@nt_type;
    Production {
        lhs: 7,
        production: &[
            ParseType::N(48),
            ParseType::T(9),
            ParseType::N(13),
            ParseType::T(10),
        ],
    },
    // 11 - Declaration: "%t_type" UserTypeName@t_type;
    Production {
        lhs: 7,
        production: &[ParseType::N(48), ParseType::T(11)],
    },
    // 12 - Declaration: '%grammar_type' LiteralString;
    Production {
        lhs: 7,
        production: &[ParseType::N(16), ParseType::T(12)],
    },
    // 13 - Declaration: ScannerDirectives;
    Production {
        lhs: 7,
        production: &[ParseType::N(33)],
    },
    // 14 - ScannerDirectives: "%line_comment" TokenLiteral;
    Production {
        lhs: 33,
        production: &[ParseType::N(44), ParseType::T(13)],
    },
    // 15 - ScannerDirectives: "%block_comment" TokenLiteral TokenLiteral;
    Production {
        lhs: 33,
        production: &[ParseType::N(44), ParseType::N(44), ParseType::T(14)],
    },
    // 16 - ScannerDirectives: "%auto_newline_off";
    Production {
        lhs: 33,
        production: &[ParseType::T(15)],
    },
    // 17 - ScannerDirectives: "%auto_ws_off";
    Production {
        lhs: 33,
        production: &[ParseType::T(16)],
    },
    // 18 - ScannerDirectives: '%skip' IdentifierList;
    Production {
        lhs: 33,
        production: &[ParseType::N(14), ParseType::T(17)],
    },
    // 19 - ScannerDirectives: '%on' IdentifierList ScannerStateDirectives;
    Production {
        lhs: 33,
        production: &[ParseType::N(35), ParseType::N(14), ParseType::T(18)],
    },
    // 20 - ScannerDirectives: "%allow_unmatched";
    Production {
        lhs: 33,
        production: &[ParseType::T(19)],
    },
    // 21 - ScannerStateDirectives: '%enter' Identifier;
    Production {
        lhs: 35,
        production: &[ParseType::N(13), ParseType::T(20)],
    },
    // 22 - ScannerStateDirectives: '%push' Identifier;
    Production {
        lhs: 35,
        production: &[ParseType::N(13), ParseType::T(21)],
    },
    // 23 - ScannerStateDirectives: '%pop';
    Production {
        lhs: 35,
        production: &[ParseType::T(22)],
    },
    // 24 - GrammarDefinition: "%%" Production GrammarDefinitionList /* Vec */;
    Production {
        lhs: 10,
        production: &[ParseType::N(11), ParseType::N(26), ParseType::T(23)],
    },
    // 25 - GrammarDefinitionList: Production GrammarDefinitionList;
    Production {
        lhs: 11,
        production: &[ParseType::N(11), ParseType::N(26)],
    },
    // 26 - GrammarDefinitionList: ;
    Production {
        lhs: 11,
        production: &[],
    },
    // 27 - DoubleColon: "::";
    Production {
        lhs: 8,
        production: &[ParseType::T(24)],
    },
    // 28 - ProductionLHS: Identifier ":";
    Production {
        lhs: 27,
        production: &[ParseType::T(25), ParseType::N(13)],
    },
    // 29 - Production: ProductionLHS Alternations ";";
    Production {
        lhs: 26,
        production: &[ParseType::T(26), ParseType::N(4), ParseType::N(27)],
    },
    // 30 - Alternations: Alternation AlternationsList /* Vec */;
    Production {
        lhs: 4,
        production: &[ParseType::N(5), ParseType::N(2)],
    },
    // 31 - AlternationsList: '|' Alternation AlternationsList;
    Production {
        lhs: 5,
        production: &[ParseType::N(5), ParseType::N(2), ParseType::T(27)],
    },
    // 32 - AlternationsList: ;
    Production {
        lhs: 5,
        production: &[],
    },
    // 33 - Alternation: AlternationList /* Vec */;
    Production {
        lhs: 2,
        production: &[ParseType::N(3)],
    },
    // 34 - AlternationList: Factor AlternationList;
    Production {
        lhs: 3,
        production: &[ParseType::N(3), ParseType::N(9)],
    },
    // 35 - AlternationList: ;
    Production {
        lhs: 3,
        production: &[],
    },
    // 36 - Factor: Group;
    Production {
        lhs: 9,
        production: &[ParseType::N(12)],
    },
    // 37 - Factor: Repeat;
    Production {
        lhs: 9,
        production: &[ParseType::N(32)],
    },
    // 38 - Factor: Optional;
    Production {
        lhs: 9,
        production: &[ParseType::N(23)],
    },
    // 39 - Factor: Symbol;
    Production {
        lhs: 9,
        production: &[ParseType::N(41)],
    },
    // 40 - Symbol: NonTerminal;
    Production {
        lhs: 41,
        production: &[ParseType::N(21)],
    },
    // 41 - Symbol: SimpleToken;
    Production {
        lhs: 41,
        production: &[ParseType::N(37)],
    },
    // 42 - Symbol: TokenWithStates;
    Production {
        lhs: 41,
        production: &[ParseType::N(45)],
    },
    // 43 - TokenLiteral: String;
    Production {
        lhs: 44,
        production: &[ParseType::N(40)],
    },
    // 44 - TokenLiteral: LiteralString;
    Production {
        lhs: 44,
        production: &[ParseType::N(16)],
    },
    // 45 - TokenLiteral: Regex;
    Production {
        lhs: 44,
        production: &[ParseType::N(31)],
    },
    // 46 - TokenExpression: TokenLiteral TokenExpressionOpt /* Option */;
    Production {
        lhs: 42,
        production: &[ParseType::N(43), ParseType::N(44)],
    },
    // 47 - TokenExpressionOpt: LookAhead;
    Production {
        lhs: 43,
        production: &[ParseType::N(17)],
    },
    // 48 - TokenExpressionOpt: ;
    Production {
        lhs: 43,
        production: &[],
    },
    // 49 - SimpleToken: TokenExpression SimpleTokenOpt /* Option */;
    Production {
        lhs: 37,
        production: &[ParseType::N(38), ParseType::N(42)],
    },
    // 50 - SimpleTokenOpt: ASTControl;
    Production {
        lhs: 38,
        production: &[ParseType::N(0)],
    },
    // 51 - SimpleTokenOpt: ;
    Production {
        lhs: 38,
        production: &[],
    },
    // 52 - TokenWithStates: "<" IdentifierList ">" TokenExpression TokenWithStatesOpt /* Option */;
    Production {
        lhs: 45,
        production: &[
            ParseType::N(46),
            ParseType::N(42),
            ParseType::T(29),
            ParseType::N(14),
            ParseType::T(28),
        ],
    },
    // 53 - TokenWithStatesOpt: ASTControl;
    Production {
        lhs: 46,
        production: &[ParseType::N(0)],
    },
    // 54 - TokenWithStatesOpt: ;
    Production {
        lhs: 46,
        production: &[],
    },
    // 55 - Group: '(' Alternations ')';
    Production {
        lhs: 12,
        production: &[ParseType::T(31), ParseType::N(4), ParseType::T(30)],
    },
    // 56 - Optional: '[' Alternations ']';
    Production {
        lhs: 23,
        production: &[ParseType::T(33), ParseType::N(4), ParseType::T(32)],
    },
    // 57 - Repeat: '{' Alternations '}';
    Production {
        lhs: 32,
        production: &[ParseType::T(35), ParseType::N(4), ParseType::T(34)],
    },
    // 58 - NonTerminal: Identifier NonTerminalOpt /* Option */;
    Production {
        lhs: 21,
        production: &[ParseType::N(22), ParseType::N(13)],
    },
    // 59 - NonTerminalOpt: ASTControl;
    Production {
        lhs: 22,
        production: &[ParseType::N(0)],
    },
    // 60 - NonTerminalOpt: ;
    Production {
        lhs: 22,
        production: &[],
    },
    // 61 - Identifier: /[a-zA-Z_][a-zA-Z0-9_]*/;
    Production {
        lhs: 13,
        production: &[ParseType::T(36)],
    },
    // 62 - String: /"(\\.|[^"])*"/;
    Production {
        lhs: 40,
        production: &[ParseType::T(37)],
    },
    // 63 - LiteralString: /'(\\.|[^'])*'/;
    Production {
        lhs: 16,
        production: &[ParseType::T(38)],
    },
    // 64 - ScannerState: "%scanner" Identifier '{' ScannerStateList /* Vec */ '}';
    Production {
        lhs: 34,
        production: &[
            ParseType::T(35),
            ParseType::N(36),
            ParseType::T(34),
            ParseType::N(13),
            ParseType::T(39),
        ],
    },
    // 65 - ScannerStateList: ScannerDirectives ScannerStateList;
    Production {
        lhs: 36,
        production: &[ParseType::N(36), ParseType::N(33)],
    },
    // 66 - ScannerStateList: ;
    Production {
        lhs: 36,
        production: &[],
    },
    // 67 - IdentifierList: Identifier IdentifierListList /* Vec */;
    Production {
        lhs: 14,
        production: &[ParseType::N(15), ParseType::N(13)],
    },
    // 68 - IdentifierListList: "," Identifier IdentifierListList;
    Production {
        lhs: 15,
        production: &[ParseType::N(15), ParseType::N(13), ParseType::T(40)],
    },
    // 69 - IdentifierListList: ;
    Production {
        lhs: 15,
        production: &[],
    },
    // 70 - ASTControl: CutOperator;
    Production {
        lhs: 0,
        production: &[ParseType::N(6)],
    },
    // 71 - ASTControl: MemberName ASTControlOpt /* Option */;
    Production {
        lhs: 0,
        production: &[ParseType::N(1), ParseType::N(19)],
    },
    // 72 - ASTControl: UserTypeDeclaration;
    Production {
        lhs: 0,
        production: &[ParseType::N(47)],
    },
    // 73 - ASTControlOpt: UserTypeDeclaration;
    Production {
        lhs: 1,
        production: &[ParseType::N(47)],
    },
    // 74 - ASTControlOpt: ;
    Production {
        lhs: 1,
        production: &[],
    },
    // 75 - MemberName: '@'^ /* Clipped */ Identifier;
    Production {
        lhs: 19,
        production: &[ParseType::N(13), ParseType::T(41)],
    },
    // 76 - CutOperator: '^';
    Production {
        lhs: 6,
        production: &[ParseType::T(42)],
    },
    // 77 - UserTypeDeclaration: ":" UserTypeName;
    Production {
        lhs: 47,
        production: &[ParseType::N(48), ParseType::T(25)],
    },
    // 78 - UserTypeName: Identifier UserTypeNameList /* Vec */;
    Production {
        lhs: 48,
        production: &[ParseType::N(49), ParseType::N(13)],
    },
    // 79 - UserTypeNameList: DoubleColon Identifier UserTypeNameList;
    Production {
        lhs: 49,
        production: &[ParseType::N(49), ParseType::N(13), ParseType::N(8)],
    },
    // 80 - UserTypeNameList: ;
    Production {
        lhs: 49,
        production: &[],
    },
    // 81 - Regex: "/(\\.|[^\/])*/";
    Production {
        lhs: 31,
        production: &[ParseType::T(43)],
    },
    // 82 - LookAhead: LookAheadGroup TokenLiteral;
    Production {
        lhs: 17,
        production: &[ParseType::N(44), ParseType::N(18)],
    },
    // 83 - LookAheadGroup: PositiveLookahead;
    Production {
        lhs: 18,
        production: &[ParseType::N(25)],
    },
    // 84 - LookAheadGroup: NegativeLookahead;
    Production {
        lhs: 18,
        production: &[ParseType::N(20)],
    },
    // 85 - PositiveLookahead: '?=';
    Production {
        lhs: 25,
        production: &[ParseType::T(44)],
    },
    // 86 - NegativeLookahead: '?!';
    Production {
        lhs: 20,
        production: &[ParseType::T(45)],
    },
];

pub fn parse<T>(
    input: &str,
    file_name: T,
    user_actions: &mut ParolLsGrammar,
) -> Result<ParseTree, ParolError>
where
    T: AsRef<Path>,
{
    use parol_runtime::{
        parser::{parse_tree_type::SynTree, parser_types::SynTreeFlavor},
        syntree::Builder,
    };
    let mut builder = Builder::<SynTree, SynTreeFlavor>::new_with();
    parse_into(input, &mut builder, file_name, user_actions)?;
    Ok(builder.build()?)
}
#[allow(dead_code)]
pub fn parse_into<'t, T: TreeConstruct<'t>>(
    input: &'t str,
    tree_builder: &mut T,
    file_name: impl AsRef<Path>,
    user_actions: &mut ParolLsGrammar,
) -> Result<(), ParolError>
where
    ParolError: From<T::Error>,
{
    use parol_ls_grammar_scanner::ParolLsGrammarScanner;
    let mut llk_parser = LLKParser::new(
        24,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    llk_parser.trim_parse_tree();
    let scanner = ParolLsGrammarScanner::new();
    // Initialize wrapper
    let mut user_actions = ParolLsGrammarAuto::new(user_actions);
    llk_parser.parse_into(
        tree_builder,
        TokenStream::new_with_skip_tokens(
            input,
            file_name,
            scanner.scanner_impl.clone(),
            &ParolLsGrammarScanner::match_function,
            MAX_K,
            SKIP_TOKENS_BY_SCANNER_STATE,
        )
        .unwrap(),
        &mut user_actions,
    )
}
